# Site settings
title: Wander Lairson Costa
email: wander.lairson@gmail.com
description: "Hacking stuff"
baseurl: "/"
url: "https://walac.github.io"
twitter_username: walac00
github_username: walac
disqus_username: false
isso_domain: comments.mysite.org

# Build settings
markdown: redcarpet
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
